-- ENUM TYPES
CREATE TYPE public.attachment_type_enum AS ENUM (
    'image',
    'document',
    'invoice',
    'contract',
    'proposal',
    'other'
);
CREATE TYPE public.call_outcome_enum AS ENUM (
    'do not call',
    'did not dial',
    'no answer',
    'gatekeeper',
    'voicemail',
    'DM introduction',
    'DM short story',
    'DM discovery',
    'DM presentation',
    'DM resume request',
    'discovery in progress',
    'strategy call booked',
    'strategy call attended',
    'strategy call no show',
    'strategy call rescheduled',
    'operations audit booked',
    'operations audit attended',
    'operations audit no show',
    'operations audit rescheduled',
    'candidate interview booked',
    'candidate interview attended',
    'candidate interview no show',
    'candidate interview rescheduled',
    'awaiting docs',
    'deal won',
    'not interested',
    'no show',
    'onboarding call booked',
    'onboarding call attended',
    'nurturing'
);
CREATE TYPE public.deal_stage_enum AS ENUM (
    'not contacted',
    'no answer / gatekeeper',
    'decision maker',
    'nurturing',
    'interested',
    'strategy call booked',
    'strategy call attended',
    'proposal / scope',
    'closed won',
    'closed lost',
    'uncontacted',
    'dm connected',
    'bizops audit agreement sent',
    'bizops audit paid / booked',
    'bizops audit attended',
    'ms agreement sent',
    'balance paid / deal won',
    'not qualified',
    'onboarding call booked',
    'onboarding call attended',
    'active client (operator)',
    'active client - project in progress',
    'paused client',
    'candidate replacement',
    'project rescope / expansion',
    'active client - project maintenance',
    'cancelled / completed',
    'not interested',
    'candidate interview booked',
    'candidate interview attended',
    'deal won',
    'discovery',
    'proposal sent',
    'negotiation',
    'onboarding',
    'active',
    'at risk',
    'churned',
    'renewed',
    'everyday',
    'dmconnected',
    'proposal',
    'new',
    'contacted',
    'qualified',
    'meeting scheduled',
    'meeting completed',
    'demo scheduled',
    'demo completed',
    'won',
    'lost',
    'lead',
    'prospect',
    'opportunity',
    'follow up',
    'contract sent',
    'contract signed',
    'awaiting docs / signature',
    'business audit booked',
    'business audit attended',
    'not qualified / disqualified',
    'do not call',
    'awaiting docs',
    'signature',
    'docs / signature',
    'active clients (launched)',
    'paused clients',
    'cancelled clients',
    'active clients',
    'launched',
    'paused',
    'cancelled',
    'replacement'
);
CREATE TYPE public.deal_status_enum AS ENUM (
    'open',
    'won',
    'lost',
    'on_hold'
);
CREATE TYPE public.deal_vertical_enum AS ENUM (
    'Real Estate',
    'Dentals',
    'Legal',
    'Professional Services',
    'Accounting & Bookkeeping Firms',
    'Financial Advisors / Wealth Management',
    'Mortgage Brokers',
    'Consulting Firms (Business / Management / HR)',
    'Recruiting & Staffing Agencies',
    'Architecture Firms',
    'Engineering Firms',
    'Property Management Companies',
    'Web Design & Development Agencies',
    'Video Production Studios',
    'E-commerce Brands / Shopify Stores',
    'Influencers & Personal Brands',
    'Podcast Production Companies',
    'PR & Communications Agencies',
    'Graphic Design / Branding Studios',
    'Medical Clinics (Private Practices)',
    'Chiropractors',
    'Physical Therapy Clinics',
    'Nutritionists & Dietitians',
    'Mental Health Therapists / Coaches',
    'Medical Billing Companies',
    'Cleaning Companies',
    'HVAC / Plumbing / Electrical Contractors',
    'Landscaping / Lawn Care Companies',
    'Construction & Renovation Firms',
    'Pest Control Companies',
    'Online Course Creators / EdTech',
    'Life Coaches & Business Coaches',
    'Tutoring & Test Prep Centers',
    'Freight Brokerage / Dispatch Services',
    'Wholesale & Distribution Companies',
    'Automotive Dealerships or Brokers',
    'Other'
);
CREATE TYPE public.email_status_enum AS ENUM (
    'sent',
    'delivered',
    'opened',
    'clicked',
    'bounced',
    'failed'
);
CREATE TYPE public.lifecycle_stage_enum AS ENUM (
    'lead',
    'prospect',
    'qualified',
    'customer',
    'evangelist'
);
CREATE TYPE public.meeting_outcome_enum AS ENUM (
    'Client - Resolved',
    'Client - Revisit',
    'Client - Positive',
    'Client - Neutral',
    'Client - Negative',
    'Client - Risk Churn',
    'Client - Upsell Opportunity',
    'Client - Referral Opportunity',
    'Operator - Resolved',
    'Operator - Revisit',
    'Operator - Aligned',
    'Operator - Overwhelmed',
    'Operator - At Risk'
);
CREATE TYPE public.meeting_type_enum AS ENUM (
    'Client Check-In',
    'Client Strategy Session',
    'Client Resolution Meeting',
    'Campaign Alignment (Client + Operator)',
    'Referral Request Meeting',
    'Upsell/Downsell Conversation',
    'Operator Leadership Meeting',
    'Operator Resolution Meeting',
    'Internal Performance Alignment'
);
CREATE TYPE public.outbound_type_enum AS ENUM (
    'outbound call',
    'inbound call',
    'strategy call',
    'operations audit',
    'candidate interview',
    'onboarding call'
);
CREATE TYPE public.priority_enum AS ENUM (
    'high',
    'medium',
    'low'
);
CREATE TYPE public.product_category_enum AS ENUM (
    'VA',
    'SMM',
    'Web',
    'Webapp',
    'AI Adoption',
    'Other'
);
CREATE TYPE public.qualification_status_enum AS ENUM (
    'sql',
    'nql',
    'unknown'
);
CREATE TYPE public.task_status_enum AS ENUM (
    'pending',
    'in_progress',
    'completed',
    'cancelled',
    'rescheduled'
);

