-- First, let's add some test data for testing purposes

-- Insert test companies
INSERT INTO companies (name, website, phone, address, industry, employees_count, city, state, country, timezone, description, linkedin_url) VALUES
('TechCorp Inc.', 'https://techcorp.com', '+1-555-0101', '123 Tech St, Suite 100', 'Technology', 250, 'San Francisco', 'CA', 'USA', 'America/Los_Angeles', 'Leading technology solutions provider', 'https://linkedin.com/company/techcorp'),
('Global Solutions Ltd.', 'https://globalsolutions.com', '+1-555-0102', '456 Business Ave', 'Consulting', 150, 'New York', 'NY', 'USA', 'America/New_York', 'International business consulting firm', 'https://linkedin.com/company/globalsolutions'),
('StartupHub Co.', 'https://startuphub.com', '+1-555-0103', '789 Innovation Dr', 'Software', 50, 'Austin', 'TX', 'USA', 'America/Chicago', 'Early stage startup accelerator', 'https://linkedin.com/company/startuphub'),
('MegaCorp Industries', 'https://megacorp.com', '+1-555-0104', '321 Corporate Blvd', 'Manufacturing', 1000, 'Chicago', 'IL', 'USA', 'America/Chicago', 'Large scale manufacturing company', 'https://linkedin.com/company/megacorp'),
('InnovateTech', 'https://innovatetech.io', '+1-555-0105', '654 Future Ln', 'AI/ML', 75, 'Seattle', 'WA', 'USA', 'America/Los_Angeles', 'AI and machine learning solutions', 'https://linkedin.com/company/innovatetech');

-- Insert test contacts linked to companies
INSERT INTO contacts (first_name, last_name, email, phone, mobile, secondary_phone, city, state, country, timezone, company_id, lifecycle_stage, last_contacted_at) VALUES
('John', 'Smith', 'john.smith@techcorp.com', '+1-555-1001', '+1-555-1002', '+1-555-1003', 'San Francisco', 'CA', 'USA', 'America/Los_Angeles', (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1), 'qualified', '2024-01-15 14:30:00'),
('Sarah', 'Johnson', 'sarah.johnson@globalsolutions.com', '+1-555-1004', '+1-555-1005', NULL, 'New York', 'NY', 'USA', 'America/New_York', (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1), 'prospect', '2024-01-14 10:15:00'),
('Mike', 'Davis', 'mike.davis@startuphub.com', '+1-555-1006', '+1-555-1007', NULL, 'Austin', 'TX', 'USA', 'America/Chicago', (SELECT id FROM companies WHERE name = 'StartupHub Co.' LIMIT 1), 'lead', '2024-01-13 16:45:00'),
('Emily', 'Wilson', 'emily.wilson@megacorp.com', '+1-555-1008', '+1-555-1009', '+1-555-1010', 'Chicago', 'IL', 'USA', 'America/Chicago', (SELECT id FROM companies WHERE name = 'MegaCorp Industries' LIMIT 1), 'customer', '2024-01-12 09:20:00'),
('David', 'Brown', 'david.brown@innovatetech.io', '+1-555-1011', '+1-555-1012', NULL, 'Seattle', 'WA', 'USA', 'America/Los_Angeles', (SELECT id FROM companies WHERE name = 'InnovateTech' LIMIT 1), 'qualified', '2024-01-11 13:10:00');

-- Insert test deals linked to companies and contacts
INSERT INTO deals (name, amount, stage, priority, deal_status, close_date, timezone, currency, description, source, company_id, primary_contact_id, income_amount, contact_attempts, last_contact_date) VALUES
('TechCorp Integration Project', 85000, 'strategy call booked', 'high', 'open', '2024-02-15', 'America/Los_Angeles', 'USD', 'Large scale integration project for TechCorp platform architecture', 'Website', (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@techcorp.com' LIMIT 1), 100000, 3, '2024-01-15 14:30:00'),
('Global Solutions Consulting', 45000, 'proposal', 'medium', 'open', '2024-02-28', 'America/New_York', 'USD', 'Strategic consulting engagement for digital transformation', 'Referral', (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1), (SELECT id FROM contacts WHERE email = 'sarah.johnson@globalsolutions.com' LIMIT 1), 60000, 2, '2024-01-14 10:15:00'),
('StartupHub MVP Development', 25000, 'nurturing', 'low', 'open', '2024-03-10', 'America/Chicago', 'USD', 'MVP development for new startup in the accelerator program', 'Cold Outbound', (SELECT id FROM companies WHERE name = 'StartupHub Co.' LIMIT 1), (SELECT id FROM contacts WHERE email = 'mike.davis@startuphub.com' LIMIT 1), 35000, 1, '2024-01-13 16:45:00'),
('MegaCorp Digital Upgrade', 150000, 'decision maker', 'high', 'open', '2024-01-30', 'America/Chicago', 'USD', 'Enterprise-wide digital infrastructure upgrade project', 'LinkedIn', (SELECT id FROM companies WHERE name = 'MegaCorp Industries' LIMIT 1), (SELECT id FROM contacts WHERE email = 'emily.wilson@megacorp.com' LIMIT 1), 200000, 4, '2024-01-12 09:20:00'),
('InnovateTech AI Platform', 75000, 'closed won', 'medium', 'closed', '2024-01-20', 'America/Los_Angeles', 'USD', 'AI platform development and deployment', 'Webinar', (SELECT id FROM companies WHERE name = 'InnovateTech' LIMIT 1), (SELECT id FROM contacts WHERE email = 'david.brown@innovatetech.io' LIMIT 1), 90000, 5, '2024-01-20 15:00:00');

-- Insert test tasks linked to deals and contacts
INSERT INTO tasks (title, description, status, priority, due_date, deal_id, contact_id, company_id, created_by, assigned_to, notes) VALUES
('Follow up on TechCorp proposal', 'Call John Smith to discuss the integration project timeline and answer any questions', 'pending', 'high', '2024-01-16 10:00:00', (SELECT id FROM deals WHERE name = 'TechCorp Integration Project' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@techcorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1), NULL, NULL, 'Focus on timeline and technical requirements'),
('Send contract to Global Solutions', 'Prepare and send signed contract for consulting engagement', 'pending', 'medium', '2024-01-17 14:00:00', (SELECT id FROM deals WHERE name = 'Global Solutions Consulting' LIMIT 1), (SELECT id FROM contacts WHERE email = 'sarah.johnson@globalsolutions.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1), NULL, NULL, 'Include SOW and payment terms'),
('Research MegaCorp requirements', 'Deep dive into MegaCorp current infrastructure and digital transformation needs', 'in_progress', 'high', '2024-01-18 09:00:00', (SELECT id FROM deals WHERE name = 'MegaCorp Digital Upgrade' LIMIT 1), (SELECT id FROM contacts WHERE email = 'emily.wilson@megacorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'MegaCorp Industries' LIMIT 1), NULL, NULL, 'Focus on scalability and compliance requirements'),
('Schedule demo for StartupHub', 'Set up product demo for the MVP development project', 'pending', 'low', '2024-01-19 15:00:00', (SELECT id FROM deals WHERE name = 'StartupHub MVP Development' LIMIT 1), (SELECT id FROM contacts WHERE email = 'mike.davis@startuphub.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'StartupHub Co.' LIMIT 1), NULL, NULL, 'Show core features and customization options'),
('InnovateTech project kickoff', 'Initiate project kickoff meeting for AI platform development', 'completed', 'medium', '2024-01-20 11:00:00', (SELECT id FROM deals WHERE name = 'InnovateTech AI Platform' LIMIT 1), (SELECT id FROM contacts WHERE email = 'david.brown@innovatetech.io' LIMIT 1), (SELECT id FROM companies WHERE name = 'InnovateTech' LIMIT 1), NULL, NULL, 'Project successfully launched'),
('Cold outreach - Tech sector', 'Reach out to 10 potential tech companies this week', 'pending', 'medium', '2024-01-22 09:00:00', NULL, NULL, NULL, NULL, NULL, 'Focus on companies with 100-500 employees'),
('Update CRM data', 'Clean up and update contact information in the database', 'pending', 'low', '2024-01-25 16:00:00', NULL, NULL, NULL, NULL, NULL, 'Remove duplicates and verify email addresses');

-- Insert test calls
INSERT INTO calls (call_timestamp, duration_seconds, call_outcome, outbound_type, notes, related_deal_id, related_contact_id, related_company_id) VALUES
('2024-01-15 14:30:00', 1800, 'interested', 'outbound', 'Great conversation about technical requirements. Next steps: send detailed proposal.', (SELECT id FROM deals WHERE name = 'TechCorp Integration Project' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@techcorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1)),
('2024-01-14 10:15:00', 900, 'callback_scheduled', 'outbound', 'Initial interest shown. Scheduled follow-up call for next week.', (SELECT id FROM deals WHERE name = 'Global Solutions Consulting' LIMIT 1), (SELECT id FROM contacts WHERE email = 'sarah.johnson@globalsolutions.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1)),
('2024-01-13 16:45:00', 600, 'no_answer', 'outbound', 'Left voicemail with callback request.', (SELECT id FROM deals WHERE name = 'StartupHub MVP Development' LIMIT 1), (SELECT id FROM contacts WHERE email = 'mike.davis@startuphub.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'StartupHub Co.' LIMIT 1));

-- Insert test meetings
INSERT INTO meetings (title, description, scheduled_at, duration_minutes, meeting_type, is_booked, is_attended, location, meeting_link, notes, deal_id, contact_id, company_id) VALUES
('TechCorp Strategy Call', 'Discuss integration project requirements and timeline', '2024-01-20 10:00:00', 60, 'consultation', true, true, 'Video Conference', 'https://zoom.us/j/123456789', 'Productive meeting, moving forward with proposal', (SELECT id FROM deals WHERE name = 'TechCorp Integration Project' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@techcorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1)),
('Global Solutions Discovery', 'Initial discovery call to understand consulting needs', '2024-01-22 14:00:00', 45, 'discovery', true, false, 'Conference Room A', NULL, 'Scheduled but not yet attended', (SELECT id FROM deals WHERE name = 'Global Solutions Consulting' LIMIT 1), (SELECT id FROM contacts WHERE email = 'sarah.johnson@globalsolutions.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1)),
('MegaCorp Requirements Review', 'Technical requirements review for digital upgrade project', '2024-01-25 15:30:00', 90, 'technical', true, false, 'Client Office', NULL, 'Upcoming technical review meeting', (SELECT id FROM deals WHERE name = 'MegaCorp Digital Upgrade' LIMIT 1), (SELECT id FROM contacts WHERE email = 'emily.wilson@megacorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'MegaCorp Industries' LIMIT 1));

-- Insert test emails
INSERT INTO emails (subject, body, from_email, to_email, status, sent_at, opened_at, clicked_at, deal_id, contact_id, company_id) VALUES
('TechCorp Integration Proposal', 'Hi John, Thank you for the great conversation yesterday. As discussed, I''ve attached our detailed proposal for the integration project...', 'sales@company.com', 'john.smith@techcorp.com', 'opened', '2024-01-16 09:00:00', '2024-01-16 09:15:00', '2024-01-16 09:20:00', (SELECT id FROM deals WHERE name = 'TechCorp Integration Project' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@techcorp.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'TechCorp Inc.' LIMIT 1)),
('Global Solutions Consulting Opportunity', 'Hi Sarah, It was great connecting with you on LinkedIn. I''d love to discuss how we can help with your digital transformation initiative...', 'sales@company.com', 'sarah.johnson@globalsolutions.com', 'sent', '2024-01-13 11:30:00', NULL, NULL, (SELECT id FROM deals WHERE name = 'Global Solutions Consulting' LIMIT 1), (SELECT id FROM contacts WHERE email = 'sarah.johnson@globalsolutions.com' LIMIT 1), (SELECT id FROM companies WHERE name = 'Global Solutions Ltd.' LIMIT 1)),
('InnovateTech Project Update', 'Hi David, Quick update on the AI platform project - we''re on track for the Q1 delivery...', 'sales@company.com', 'david.brown@innovatetech.io', 'clicked', '2024-01-21 16:00:00', '2024-01-21 16:05:00', '2024-01-21 16:07:00', (SELECT id FROM deals WHERE name = 'InnovateTech AI Platform' LIMIT 1), (SELECT id FROM contacts WHERE email = 'david.brown@innovatetech.io' LIMIT 1), (SELECT id FROM companies WHERE name = 'InnovateTech' LIMIT 1));