// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = (typeof window !== 'undefined' ? (window as any)?.env?.VITE_SUPABASE_URL : undefined) || import.meta.env.VITE_SUPABASE_URL || "https://qzxuhefnyskdtdfrcrtg.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = (typeof window !== 'undefined' ? (window as any)?.env?.VITE_SUPABASE_ANON_KEY : undefined) || import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eHVoZWZueXNrZHRkZnJjcnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDkwNjMsImV4cCI6MjA3MzI4NTA2M30.bWxU18LllaPPksIDSPsuHaj785EVWHcoEZj8jfLFoXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});